// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollkitsdk/sequencer/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QuerySequencersChangesRequest is request type for the Query/SequencersChanges RPC method.
type QuerySequencersChangesRequest struct {
}

func (m *QuerySequencersChangesRequest) Reset()         { *m = QuerySequencersChangesRequest{} }
func (m *QuerySequencersChangesRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySequencersChangesRequest) ProtoMessage()    {}
func (*QuerySequencersChangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8891a1048a0af2d9, []int{0}
}
func (m *QuerySequencersChangesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencersChangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencersChangesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencersChangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencersChangesRequest.Merge(m, src)
}
func (m *QuerySequencersChangesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencersChangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencersChangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencersChangesRequest proto.InternalMessageInfo

// QuerySequencersChangesResponse is response type for the Query/SequencersChanges RPC method.
type QuerySequencersChangesResponse struct {
	// sequencer_changes is the list of sequencer changes.
	SequencerChanges []SequencerChanges `protobuf:"bytes,1,rep,name=sequencer_changes,json=sequencerChanges,proto3" json:"sequencer_changes"`
}

func (m *QuerySequencersChangesResponse) Reset()         { *m = QuerySequencersChangesResponse{} }
func (m *QuerySequencersChangesResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySequencersChangesResponse) ProtoMessage()    {}
func (*QuerySequencersChangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8891a1048a0af2d9, []int{1}
}
func (m *QuerySequencersChangesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencersChangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencersChangesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencersChangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencersChangesResponse.Merge(m, src)
}
func (m *QuerySequencersChangesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencersChangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencersChangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencersChangesResponse proto.InternalMessageInfo

func (m *QuerySequencersChangesResponse) GetSequencerChanges() []SequencerChanges {
	if m != nil {
		return m.SequencerChanges
	}
	return nil
}

// QuerySequencersRequest is request type for the Query/Sequencers RPC method.
type QuerySequencersRequest struct {
}

func (m *QuerySequencersRequest) Reset()         { *m = QuerySequencersRequest{} }
func (m *QuerySequencersRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySequencersRequest) ProtoMessage()    {}
func (*QuerySequencersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8891a1048a0af2d9, []int{2}
}
func (m *QuerySequencersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencersRequest.Merge(m, src)
}
func (m *QuerySequencersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencersRequest proto.InternalMessageInfo

// QuerySequencersResponse is response type for the Query/Sequencers RPC method.
type QuerySequencersResponse struct {
	// sequencers is the list of sequencers.
	Sequencers []Sequencer `protobuf:"bytes,1,rep,name=sequencers,proto3" json:"sequencers"`
}

func (m *QuerySequencersResponse) Reset()         { *m = QuerySequencersResponse{} }
func (m *QuerySequencersResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySequencersResponse) ProtoMessage()    {}
func (*QuerySequencersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8891a1048a0af2d9, []int{3}
}
func (m *QuerySequencersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencersResponse.Merge(m, src)
}
func (m *QuerySequencersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencersResponse proto.InternalMessageInfo

func (m *QuerySequencersResponse) GetSequencers() []Sequencer {
	if m != nil {
		return m.Sequencers
	}
	return nil
}

func init() {
	proto.RegisterType((*QuerySequencersChangesRequest)(nil), "rollkitsdk.sequencer.v1.QuerySequencersChangesRequest")
	proto.RegisterType((*QuerySequencersChangesResponse)(nil), "rollkitsdk.sequencer.v1.QuerySequencersChangesResponse")
	proto.RegisterType((*QuerySequencersRequest)(nil), "rollkitsdk.sequencer.v1.QuerySequencersRequest")
	proto.RegisterType((*QuerySequencersResponse)(nil), "rollkitsdk.sequencer.v1.QuerySequencersResponse")
}

func init() {
	proto.RegisterFile("rollkitsdk/sequencer/v1/query.proto", fileDescriptor_8891a1048a0af2d9)
}

var fileDescriptor_8891a1048a0af2d9 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0xca, 0xcf, 0xc9,
	0xc9, 0xce, 0x2c, 0x29, 0x4e, 0xc9, 0xd6, 0x2f, 0x4e, 0x2d, 0x2c, 0x4d, 0xcd, 0x4b, 0x4e, 0x2d,
	0xd2, 0x2f, 0x33, 0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x47, 0x28, 0xd2, 0x83, 0x2b, 0xd2, 0x2b, 0x33, 0x94, 0x12, 0x4c, 0xcc, 0xcd, 0xcc, 0xcb,
	0xd7, 0x07, 0x93, 0x10, 0xb5, 0x52, 0x22, 0xe9, 0xf9, 0xe9, 0xf9, 0x60, 0xa6, 0x3e, 0x88, 0x05,
	0x15, 0x95, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb,
	0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xca, 0xe2, 0x74, 0x44, 0x49, 0x65, 0x41,
	0x2a, 0x54, 0x91, 0x92, 0x3c, 0x97, 0x6c, 0x20, 0xc8, 0x4d, 0xc1, 0x30, 0x05, 0xc5, 0xce, 0x19,
	0x89, 0x79, 0xe9, 0xa9, 0xc5, 0x41, 0x20, 0x81, 0xe2, 0x12, 0xa5, 0x66, 0x46, 0x2e, 0x39, 0x5c,
	0x2a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x12, 0xb9, 0x04, 0xe1, 0xe6, 0xc7, 0x27, 0x43,
	0x24, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x34, 0xf5, 0x70, 0x78, 0x52, 0x0f, 0x6e, 0x1c,
	0xd4, 0x34, 0x27, 0xce, 0x13, 0xf7, 0xe4, 0x19, 0x56, 0x3c, 0xdf, 0xa0, 0xc5, 0x18, 0x24, 0x50,
	0x8c, 0x26, 0xa9, 0x24, 0xc1, 0x25, 0x86, 0xe6, 0x08, 0x98, 0xfb, 0x32, 0xb8, 0xc4, 0x31, 0x64,
	0xa0, 0xee, 0xf2, 0xe5, 0xe2, 0x82, 0x1b, 0x04, 0x73, 0x90, 0x12, 0x61, 0x07, 0x21, 0xbb, 0x04,
	0xc9, 0x00, 0xa3, 0x3b, 0x4c, 0x5c, 0xac, 0x60, 0xab, 0x84, 0xb6, 0x31, 0x72, 0x09, 0x62, 0x04,
	0x87, 0x90, 0x19, 0x4e, 0xa3, 0xf1, 0x86, 0xb0, 0x94, 0x39, 0xc9, 0xfa, 0x20, 0xfe, 0x53, 0x32,
	0x68, 0xba, 0xfc, 0x64, 0x32, 0x93, 0x96, 0x90, 0x86, 0x3e, 0xd4, 0x00, 0xd4, 0x68, 0x46, 0x38,
	0x1d, 0x16, 0x29, 0x42, 0x33, 0x19, 0xb9, 0xb8, 0x10, 0xe6, 0x09, 0xe9, 0x13, 0x6b, 0x33, 0xcc,
	0xa9, 0x06, 0xc4, 0x6b, 0x80, 0xba, 0x51, 0x03, 0xec, 0x46, 0x25, 0x21, 0x05, 0x42, 0x6e, 0x74,
	0x0a, 0x3b, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c,
	0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x9b, 0xf4, 0xcc, 0x92,
	0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xb8, 0x29, 0xe9, 0xf9, 0xba, 0xa9, 0x15, 0xa9, 0xc9,
	0xa5, 0xa0, 0x04, 0xaf, 0x9b, 0x98, 0x94, 0x9c, 0xa9, 0x9f, 0x9b, 0x9f, 0x52, 0x9a, 0x93, 0x5a,
	0x8c, 0x64, 0x3e, 0x38, 0x9d, 0x27, 0xb1, 0x81, 0x13, 0xba, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x11, 0x21, 0x6d, 0xa3, 0x94, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// SequencersChanges queries the sequencer changes.
	SequencersChanges(ctx context.Context, in *QuerySequencersChangesRequest, opts ...grpc.CallOption) (*QuerySequencersChangesResponse, error)
	// Sequencers queries the sequencer.
	Sequencers(ctx context.Context, in *QuerySequencersRequest, opts ...grpc.CallOption) (*QuerySequencersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) SequencersChanges(ctx context.Context, in *QuerySequencersChangesRequest, opts ...grpc.CallOption) (*QuerySequencersChangesResponse, error) {
	out := new(QuerySequencersChangesResponse)
	err := c.cc.Invoke(ctx, "/rollkitsdk.sequencer.v1.Query/SequencersChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Sequencers(ctx context.Context, in *QuerySequencersRequest, opts ...grpc.CallOption) (*QuerySequencersResponse, error) {
	out := new(QuerySequencersResponse)
	err := c.cc.Invoke(ctx, "/rollkitsdk.sequencer.v1.Query/Sequencers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// SequencersChanges queries the sequencer changes.
	SequencersChanges(context.Context, *QuerySequencersChangesRequest) (*QuerySequencersChangesResponse, error)
	// Sequencers queries the sequencer.
	Sequencers(context.Context, *QuerySequencersRequest) (*QuerySequencersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) SequencersChanges(ctx context.Context, req *QuerySequencersChangesRequest) (*QuerySequencersChangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SequencersChanges not implemented")
}
func (*UnimplementedQueryServer) Sequencers(ctx context.Context, req *QuerySequencersRequest) (*QuerySequencersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sequencers not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_SequencersChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySequencersChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SequencersChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollkitsdk.sequencer.v1.Query/SequencersChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SequencersChanges(ctx, req.(*QuerySequencersChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Sequencers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySequencersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Sequencers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollkitsdk.sequencer.v1.Query/Sequencers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Sequencers(ctx, req.(*QuerySequencersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rollkitsdk.sequencer.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SequencersChanges",
			Handler:    _Query_SequencersChanges_Handler,
		},
		{
			MethodName: "Sequencers",
			Handler:    _Query_Sequencers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollkitsdk/sequencer/v1/query.proto",
}

func (m *QuerySequencersChangesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencersChangesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencersChangesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySequencersChangesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencersChangesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencersChangesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SequencerChanges) > 0 {
		for iNdEx := len(m.SequencerChanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SequencerChanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QuerySequencersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySequencersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sequencers) > 0 {
		for iNdEx := len(m.Sequencers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sequencers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QuerySequencersChangesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySequencersChangesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SequencerChanges) > 0 {
		for _, e := range m.SequencerChanges {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QuerySequencersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySequencersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sequencers) > 0 {
		for _, e := range m.Sequencers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QuerySequencersChangesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencersChangesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencersChangesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencersChangesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencersChangesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencersChangesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequencerChanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SequencerChanges = append(m.SequencerChanges, SequencerChanges{})
			if err := m.SequencerChanges[len(m.SequencerChanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequencers = append(m.Sequencers, Sequencer{})
			if err := m.Sequencers[len(m.Sequencers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
