// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollkitsdk/sequencer/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QuerySequencerChangesRequest is request type for the Query/SequencerChanges RPC method.
type QuerySequencerChangesRequest struct {
}

func (m *QuerySequencerChangesRequest) Reset()         { *m = QuerySequencerChangesRequest{} }
func (m *QuerySequencerChangesRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySequencerChangesRequest) ProtoMessage()    {}
func (*QuerySequencerChangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8891a1048a0af2d9, []int{0}
}
func (m *QuerySequencerChangesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencerChangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencerChangesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencerChangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencerChangesRequest.Merge(m, src)
}
func (m *QuerySequencerChangesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencerChangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencerChangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencerChangesRequest proto.InternalMessageInfo

// QuerySequencerChangesResponse is response type for the Query/SequencerChanges RPC method.
type QuerySequencerChangesResponse struct {
	// sequencer_changes is the list of sequencer changes.
	SequencerChanges []SequencerChanges `protobuf:"bytes,1,rep,name=sequencer_changes,json=sequencerChanges,proto3" json:"sequencer_changes"`
}

func (m *QuerySequencerChangesResponse) Reset()         { *m = QuerySequencerChangesResponse{} }
func (m *QuerySequencerChangesResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySequencerChangesResponse) ProtoMessage()    {}
func (*QuerySequencerChangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8891a1048a0af2d9, []int{1}
}
func (m *QuerySequencerChangesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencerChangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencerChangesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencerChangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencerChangesResponse.Merge(m, src)
}
func (m *QuerySequencerChangesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencerChangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencerChangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencerChangesResponse proto.InternalMessageInfo

func (m *QuerySequencerChangesResponse) GetSequencerChanges() []SequencerChanges {
	if m != nil {
		return m.SequencerChanges
	}
	return nil
}

func init() {
	proto.RegisterType((*QuerySequencerChangesRequest)(nil), "rollkitsdk.sequencer.v1.QuerySequencerChangesRequest")
	proto.RegisterType((*QuerySequencerChangesResponse)(nil), "rollkitsdk.sequencer.v1.QuerySequencerChangesResponse")
}

func init() {
	proto.RegisterFile("rollkitsdk/sequencer/v1/query.proto", fileDescriptor_8891a1048a0af2d9)
}

var fileDescriptor_8891a1048a0af2d9 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0xca, 0xcf, 0xc9,
	0xc9, 0xce, 0x2c, 0x29, 0x4e, 0xc9, 0xd6, 0x2f, 0x4e, 0x2d, 0x2c, 0x4d, 0xcd, 0x4b, 0x4e, 0x2d,
	0xd2, 0x2f, 0x33, 0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x47, 0x28, 0xd2, 0x83, 0x2b, 0xd2, 0x2b, 0x33, 0x94, 0x12, 0x4c, 0xcc, 0xcd, 0xcc, 0xcb,
	0xd7, 0x07, 0x93, 0x10, 0xb5, 0x52, 0x22, 0xe9, 0xf9, 0xe9, 0xf9, 0x60, 0xa6, 0x3e, 0x88, 0x05,
	0x15, 0x95, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb,
	0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xca, 0xaa, 0xe2, 0x72, 0x44, 0x7a, 0x6a,
	0x5e, 0x6a, 0x71, 0x26, 0x54, 0x99, 0x92, 0x1c, 0x97, 0x4c, 0x20, 0xc8, 0x55, 0xc1, 0x30, 0x25,
	0xce, 0x19, 0x89, 0x79, 0xe9, 0xa9, 0xc5, 0x41, 0x20, 0x7e, 0x71, 0x89, 0x52, 0x13, 0x23, 0x97,
	0x2c, 0x0e, 0x05, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x89, 0x5c, 0x82, 0x70, 0xf3, 0xe3,
	0x93, 0x21, 0x92, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x9a, 0x7a, 0x38, 0x3c, 0xa9, 0x87,
	0x6e, 0x9a, 0x13, 0xe7, 0x89, 0x7b, 0xf2, 0x0c, 0x2b, 0x9e, 0x6f, 0xd0, 0x62, 0x0c, 0x12, 0x28,
	0x46, 0x93, 0x34, 0xda, 0xcc, 0xc8, 0xc5, 0x0a, 0x76, 0x84, 0xd0, 0x4a, 0x46, 0x2e, 0x41, 0xb8,
	0xde, 0x62, 0xa8, 0xbc, 0x90, 0x29, 0x4e, 0x7b, 0xf0, 0xf9, 0x4d, 0xca, 0x8c, 0x54, 0x6d, 0x10,
	0x1f, 0x2b, 0xa9, 0x36, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x5e, 0x48, 0x56, 0x1f, 0xaa, 0x1f, 0x35,
	0x80, 0xa1, 0x61, 0xe0, 0x14, 0x76, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e,
	0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51,
	0x36, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0x70, 0x23, 0xd2, 0xf3, 0x75,
	0x53, 0x2b, 0x52, 0x93, 0x4b, 0x41, 0x71, 0xa8, 0x9b, 0x98, 0x94, 0x9c, 0xa9, 0x9f, 0x9b, 0x9f,
	0x52, 0x9a, 0x93, 0x5a, 0x8c, 0x64, 0x78, 0x49, 0x65, 0x41, 0x6a, 0x71, 0x12, 0x1b, 0x38, 0xe6,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x0c, 0xb3, 0x99, 0x67, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	SequencersChanges(ctx context.Context, in *QuerySequencerChangesRequest, opts ...grpc.CallOption) (*QuerySequencerChangesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) SequencersChanges(ctx context.Context, in *QuerySequencerChangesRequest, opts ...grpc.CallOption) (*QuerySequencerChangesResponse, error) {
	out := new(QuerySequencerChangesResponse)
	err := c.cc.Invoke(ctx, "/rollkitsdk.sequencer.v1.Query/SequencersChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	SequencersChanges(context.Context, *QuerySequencerChangesRequest) (*QuerySequencerChangesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) SequencersChanges(ctx context.Context, req *QuerySequencerChangesRequest) (*QuerySequencerChangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SequencersChanges not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_SequencersChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySequencerChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SequencersChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollkitsdk.sequencer.v1.Query/SequencersChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SequencersChanges(ctx, req.(*QuerySequencerChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rollkitsdk.sequencer.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SequencersChanges",
			Handler:    _Query_SequencersChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollkitsdk/sequencer/v1/query.proto",
}

func (m *QuerySequencerChangesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencerChangesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencerChangesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySequencerChangesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencerChangesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencerChangesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SequencerChanges) > 0 {
		for iNdEx := len(m.SequencerChanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SequencerChanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QuerySequencerChangesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySequencerChangesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SequencerChanges) > 0 {
		for _, e := range m.SequencerChanges {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QuerySequencerChangesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencerChangesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencerChangesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencerChangesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencerChangesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencerChangesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequencerChanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SequencerChanges = append(m.SequencerChanges, SequencerChanges{})
			if err := m.SequencerChanges[len(m.SequencerChanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
