// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollkitsdk/sequencer/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Sequencer defines a sequence of instructions to be executed.
type Sequencer struct {
	// name is the human-readable name of the sequence.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// consensus_pubkey is the consensus public key of the sequencer, as a
	// Protobuf Any.
	ConsensusPubkey *types.Any `protobuf:"bytes,2,opt,name=consensus_pubkey,json=consensusPubkey,proto3" json:"consensus_pubkey,omitempty"`
}

func (m *Sequencer) Reset()         { *m = Sequencer{} }
func (m *Sequencer) String() string { return proto.CompactTextString(m) }
func (*Sequencer) ProtoMessage()    {}
func (*Sequencer) Descriptor() ([]byte, []int) {
	return fileDescriptor_40268d963f9caa84, []int{0}
}
func (m *Sequencer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sequencer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sequencer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Sequencer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sequencer.Merge(m, src)
}
func (m *Sequencer) XXX_Size() int {
	return m.Size()
}
func (m *Sequencer) XXX_DiscardUnknown() {
	xxx_messageInfo_Sequencer.DiscardUnknown(m)
}

var xxx_messageInfo_Sequencer proto.InternalMessageInfo

func (m *Sequencer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sequencer) GetConsensusPubkey() *types.Any {
	if m != nil {
		return m.ConsensusPubkey
	}
	return nil
}

// SequencerChanges defines a sequence of instructions to be executed.
type SequencerChanges struct {
	// block height that trigger the change sequencer
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// sequencers is the list pubkey that will become new sequencers.
	Sequencers []Sequencer `protobuf:"bytes,2,rep,name=sequencers,proto3" json:"sequencers"`
}

func (m *SequencerChanges) Reset()         { *m = SequencerChanges{} }
func (m *SequencerChanges) String() string { return proto.CompactTextString(m) }
func (*SequencerChanges) ProtoMessage()    {}
func (*SequencerChanges) Descriptor() ([]byte, []int) {
	return fileDescriptor_40268d963f9caa84, []int{1}
}
func (m *SequencerChanges) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SequencerChanges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SequencerChanges.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SequencerChanges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequencerChanges.Merge(m, src)
}
func (m *SequencerChanges) XXX_Size() int {
	return m.Size()
}
func (m *SequencerChanges) XXX_DiscardUnknown() {
	xxx_messageInfo_SequencerChanges.DiscardUnknown(m)
}

var xxx_messageInfo_SequencerChanges proto.InternalMessageInfo

func (m *SequencerChanges) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *SequencerChanges) GetSequencers() []Sequencer {
	if m != nil {
		return m.Sequencers
	}
	return nil
}

func init() {
	proto.RegisterType((*Sequencer)(nil), "rollkitsdk.sequencer.v1.Sequencer")
	proto.RegisterType((*SequencerChanges)(nil), "rollkitsdk.sequencer.v1.SequencerChanges")
}

func init() {
	proto.RegisterFile("rollkitsdk/sequencer/v1/types.proto", fileDescriptor_40268d963f9caa84)
}

var fileDescriptor_40268d963f9caa84 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x3f, 0x6b, 0xdb, 0x40,
	0x18, 0xc6, 0x75, 0xae, 0x29, 0xf8, 0x5c, 0xa8, 0x2b, 0x0c, 0x55, 0x3d, 0xa8, 0xae, 0xbb, 0x98,
	0x82, 0xef, 0xb0, 0xbb, 0x76, 0xa9, 0xbb, 0x14, 0x4a, 0xc1, 0xa8, 0x50, 0x48, 0x16, 0x23, 0x9d,
	0x2f, 0x27, 0x21, 0xe9, 0x5e, 0x45, 0xa7, 0x33, 0x51, 0xe6, 0x7c, 0x80, 0x7c, 0x8c, 0x8c, 0x19,
	0xf2, 0x21, 0x4c, 0x26, 0x8f, 0x99, 0x42, 0xb0, 0x87, 0x7c, 0x8d, 0x90, 0x93, 0xad, 0x78, 0xc9,
	0x72, 0xbc, 0xff, 0xee, 0xf7, 0xbc, 0x3c, 0x2f, 0xfe, 0x9a, 0x43, 0x92, 0xc4, 0x51, 0xa1, 0x16,
	0x31, 0x55, 0xfc, 0x54, 0x73, 0xc9, 0x78, 0x4e, 0x97, 0x63, 0x5a, 0x94, 0x19, 0x57, 0x24, 0xcb,
	0xa1, 0x00, 0xfb, 0xe3, 0xcb, 0x10, 0xa9, 0x87, 0xc8, 0x72, 0xdc, 0xfb, 0xe0, 0xa7, 0x91, 0x04,
	0x6a, 0xde, 0x6a, 0xb6, 0xf7, 0x89, 0x81, 0x4a, 0x41, 0xcd, 0x4d, 0x46, 0xab, 0x64, 0xd7, 0xea,
	0x0a, 0x10, 0x50, 0xd5, 0x9f, 0xa3, 0xfd, 0x07, 0x01, 0x20, 0x12, 0x4e, 0x4d, 0x16, 0xe8, 0x13,
	0xea, 0xcb, 0xb2, 0x6a, 0x0d, 0xce, 0x71, 0xeb, 0xdf, 0x5e, 0xce, 0xb6, 0x71, 0x53, 0xfa, 0x29,
	0x77, 0x50, 0x1f, 0x0d, 0x5b, 0x9e, 0x89, 0xed, 0x23, 0xdc, 0x61, 0x20, 0x15, 0x97, 0x4a, 0xab,
	0x79, 0xa6, 0x83, 0x98, 0x97, 0x4e, 0xa3, 0x8f, 0x86, 0xed, 0x49, 0x97, 0x54, 0x58, 0xb2, 0xc7,
	0x92, 0x9f, 0xb2, 0x9c, 0x3a, 0xb7, 0x37, 0xa3, 0xee, 0x6e, 0x27, 0x96, 0x97, 0x59, 0x01, 0x64,
	0xa6, 0x83, 0x3f, 0xbc, 0xf4, 0xde, 0xd7, 0x9c, 0x99, 0xc1, 0x0c, 0x2e, 0x10, 0xee, 0xd4, 0xe2,
	0xbf, 0x42, 0x5f, 0x0a, 0xae, 0xec, 0x2f, 0xf8, 0x5d, 0x90, 0x00, 0x8b, 0xe7, 0x21, 0x8f, 0x44,
	0x58, 0x98, 0x5d, 0x9a, 0x5e, 0xdb, 0xd4, 0x7e, 0x9b, 0x92, 0xfd, 0x17, 0xe3, 0xda, 0x22, 0xe5,
	0x34, 0xfa, 0x6f, 0x86, 0xed, 0xc9, 0x80, 0xbc, 0x62, 0x20, 0xa9, 0x15, 0xa6, 0xad, 0xd5, 0xfd,
	0x67, 0xeb, 0xea, 0xf1, 0xfa, 0x1b, 0xf2, 0x0e, 0x00, 0xd3, 0xff, 0xab, 0x8d, 0x8b, 0xd6, 0x1b,
	0x17, 0x3d, 0x6c, 0x5c, 0x74, 0xb9, 0x75, 0xad, 0xf5, 0xd6, 0xb5, 0xee, 0xb6, 0xae, 0x75, 0xfc,
	0x43, 0x44, 0x45, 0xa8, 0x03, 0xc2, 0x20, 0xa5, 0x3b, 0x3c, 0x15, 0x30, 0xe2, 0x67, 0x9c, 0xe9,
	0x22, 0x02, 0x39, 0xf2, 0x03, 0x16, 0xd1, 0x14, 0x16, 0x3a, 0xe1, 0xea, 0xe0, 0xb6, 0xe6, 0xb0,
	0xc1, 0x5b, 0xe3, 0xcb, 0xf7, 0xa7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0x4e, 0x4d, 0x89, 0x00,
	0x02, 0x00, 0x00,
}

func (m *Sequencer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sequencer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sequencer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsensusPubkey != nil {
		{
			size, err := m.ConsensusPubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SequencerChanges) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SequencerChanges) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SequencerChanges) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sequencers) > 0 {
		for iNdEx := len(m.Sequencers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sequencers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.BlockHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Sequencer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ConsensusPubkey != nil {
		l = m.ConsensusPubkey.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *SequencerChanges) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovTypes(uint64(m.BlockHeight))
	}
	if len(m.Sequencers) > 0 {
		for _, e := range m.Sequencers {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Sequencer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sequencer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sequencer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = &types.Any{}
			}
			if err := m.ConsensusPubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SequencerChanges) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SequencerChanges: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SequencerChanges: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequencers = append(m.Sequencers, Sequencer{})
			if err := m.Sequencers[len(m.Sequencers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
