version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: duplicated-imports
          severity: warning
        - name: exported
          arguments:
            - disableStutteringCheck

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: [github.com/rollkit]
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/rollkit)
        - prefix(github.com/rollkit/go-execution-abci)
      custom-order: true
