// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollkitsdk/rollkitmngr/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryIsMigratingRequest is request type for the Query/IsMigrating RPC method.
type QueryIsMigratingRequest struct {
}

func (m *QueryIsMigratingRequest) Reset()         { *m = QueryIsMigratingRequest{} }
func (m *QueryIsMigratingRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsMigratingRequest) ProtoMessage()    {}
func (*QueryIsMigratingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebbede1dda82d15, []int{0}
}
func (m *QueryIsMigratingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsMigratingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsMigratingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsMigratingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsMigratingRequest.Merge(m, src)
}
func (m *QueryIsMigratingRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsMigratingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsMigratingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsMigratingRequest proto.InternalMessageInfo

// QueryIsMigratingResponse is response type for the Query/IsMigrating RPC method.
type QueryIsMigratingResponse struct {
	// is_migrating indicates whether the chain is migrating to rollkit.
	IsMigrating bool `protobuf:"varint,1,opt,name=is_migrating,json=isMigrating,proto3" json:"is_migrating,omitempty"`
	// start_block_height is the block height at which the migration will start.
	StartBlockHeight uint64 `protobuf:"varint,2,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	// end_block_height is the block height at which the migration will end.
	EndBlockHeight uint64 `protobuf:"varint,3,opt,name=end_block_height,json=endBlockHeight,proto3" json:"end_block_height,omitempty"`
}

func (m *QueryIsMigratingResponse) Reset()         { *m = QueryIsMigratingResponse{} }
func (m *QueryIsMigratingResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIsMigratingResponse) ProtoMessage()    {}
func (*QueryIsMigratingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebbede1dda82d15, []int{1}
}
func (m *QueryIsMigratingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsMigratingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsMigratingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsMigratingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsMigratingResponse.Merge(m, src)
}
func (m *QueryIsMigratingResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsMigratingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsMigratingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsMigratingResponse proto.InternalMessageInfo

func (m *QueryIsMigratingResponse) GetIsMigrating() bool {
	if m != nil {
		return m.IsMigrating
	}
	return false
}

func (m *QueryIsMigratingResponse) GetStartBlockHeight() uint64 {
	if m != nil {
		return m.StartBlockHeight
	}
	return 0
}

func (m *QueryIsMigratingResponse) GetEndBlockHeight() uint64 {
	if m != nil {
		return m.EndBlockHeight
	}
	return 0
}

// QuerySequencerRequest is request type for the Query/Sequencer RPC method.
type QuerySequencerRequest struct {
}

func (m *QuerySequencerRequest) Reset()         { *m = QuerySequencerRequest{} }
func (m *QuerySequencerRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySequencerRequest) ProtoMessage()    {}
func (*QuerySequencerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebbede1dda82d15, []int{2}
}
func (m *QuerySequencerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencerRequest.Merge(m, src)
}
func (m *QuerySequencerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencerRequest proto.InternalMessageInfo

// QuerySequencerResponse is response type for the Query/Sequencer RPC method.
type QuerySequencerResponse struct {
	// sequencer is the requested sequencer.
	Sequencer Sequencer `protobuf:"bytes,1,opt,name=sequencer,proto3" json:"sequencer"`
}

func (m *QuerySequencerResponse) Reset()         { *m = QuerySequencerResponse{} }
func (m *QuerySequencerResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySequencerResponse) ProtoMessage()    {}
func (*QuerySequencerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebbede1dda82d15, []int{3}
}
func (m *QuerySequencerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencerResponse.Merge(m, src)
}
func (m *QuerySequencerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencerResponse proto.InternalMessageInfo

func (m *QuerySequencerResponse) GetSequencer() Sequencer {
	if m != nil {
		return m.Sequencer
	}
	return Sequencer{}
}

// QueryAttestersRequest is request type for the Query/Attesters RPC method.
type QueryAttestersRequest struct {
}

func (m *QueryAttestersRequest) Reset()         { *m = QueryAttestersRequest{} }
func (m *QueryAttestersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAttestersRequest) ProtoMessage()    {}
func (*QueryAttestersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebbede1dda82d15, []int{4}
}
func (m *QueryAttestersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestersRequest.Merge(m, src)
}
func (m *QueryAttestersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestersRequest proto.InternalMessageInfo

// QueryAttestersResponse is response type for the Query/Attesters RPC method.
type QueryAttestersResponse struct {
	// attesters is the list of attesters.
	Attesters []Attester `protobuf:"bytes,1,rep,name=attesters,proto3" json:"attesters"`
}

func (m *QueryAttestersResponse) Reset()         { *m = QueryAttestersResponse{} }
func (m *QueryAttestersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAttestersResponse) ProtoMessage()    {}
func (*QueryAttestersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ebbede1dda82d15, []int{5}
}
func (m *QueryAttestersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestersResponse.Merge(m, src)
}
func (m *QueryAttestersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestersResponse proto.InternalMessageInfo

func (m *QueryAttestersResponse) GetAttesters() []Attester {
	if m != nil {
		return m.Attesters
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryIsMigratingRequest)(nil), "rollkitsdk.rollkitmngr.v1.QueryIsMigratingRequest")
	proto.RegisterType((*QueryIsMigratingResponse)(nil), "rollkitsdk.rollkitmngr.v1.QueryIsMigratingResponse")
	proto.RegisterType((*QuerySequencerRequest)(nil), "rollkitsdk.rollkitmngr.v1.QuerySequencerRequest")
	proto.RegisterType((*QuerySequencerResponse)(nil), "rollkitsdk.rollkitmngr.v1.QuerySequencerResponse")
	proto.RegisterType((*QueryAttestersRequest)(nil), "rollkitsdk.rollkitmngr.v1.QueryAttestersRequest")
	proto.RegisterType((*QueryAttestersResponse)(nil), "rollkitsdk.rollkitmngr.v1.QueryAttestersResponse")
}

func init() {
	proto.RegisterFile("rollkitsdk/rollkitmngr/v1/query.proto", fileDescriptor_2ebbede1dda82d15)
}

var fileDescriptor_2ebbede1dda82d15 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0x8d, 0x8a, 0x99, 0x88, 0xd4, 0x41, 0x6d, 0x1a, 0x64, 0x4d, 0xd3, 0x2a, 0x51,
	0xda, 0x5d, 0x93, 0xde, 0x05, 0x73, 0x52, 0xb0, 0x07, 0xe3, 0x45, 0xbc, 0x84, 0xc9, 0x66, 0x9c,
	0x0c, 0xd9, 0x9d, 0x49, 0x67, 0x66, 0x8b, 0xbd, 0xfa, 0x09, 0x04, 0xf1, 0xe4, 0xd5, 0x83, 0x47,
	0x3f, 0x46, 0x8f, 0x05, 0x2f, 0x9e, 0x44, 0x12, 0x41, 0xf0, 0x53, 0xc8, 0x4e, 0x67, 0x27, 0x9b,
	0x94, 0x24, 0xe4, 0x12, 0x86, 0xf7, 0xfe, 0xf3, 0x9f, 0x5f, 0xf6, 0xff, 0x78, 0xf0, 0x81, 0x14,
	0x51, 0x34, 0x64, 0x5a, 0xf5, 0x87, 0x81, 0x3d, 0xc6, 0x9c, 0xca, 0xe0, 0xa4, 0x19, 0x1c, 0x27,
	0x44, 0x9e, 0xfa, 0x23, 0x29, 0xb4, 0x40, 0xdb, 0x53, 0x99, 0x9f, 0x93, 0xf9, 0x27, 0xcd, 0xea,
	0x2d, 0x1c, 0x33, 0x2e, 0x02, 0xf3, 0x7b, 0xa1, 0xae, 0xde, 0xa6, 0x82, 0x0a, 0x73, 0x0c, 0xd2,
	0x93, 0xad, 0xde, 0xa3, 0x42, 0xd0, 0x88, 0x04, 0x78, 0xc4, 0x02, 0xcc, 0xb9, 0xd0, 0x58, 0x33,
	0xc1, 0x95, 0xed, 0x2e, 0x01, 0xd1, 0xa7, 0x23, 0x62, 0x65, 0xf5, 0x6d, 0xb8, 0xf5, 0x2a, 0xe5,
	0x7a, 0xa1, 0x8e, 0x18, 0x95, 0x58, 0x33, 0x4e, 0x3b, 0xe4, 0x38, 0x21, 0x4a, 0xd7, 0x3f, 0x03,
	0x58, 0xb9, 0xdc, 0x53, 0x23, 0xc1, 0x15, 0x41, 0x3b, 0xf0, 0x06, 0x53, 0xdd, 0x38, 0xab, 0x57,
	0x40, 0x0d, 0x34, 0xae, 0x77, 0xca, 0x6c, 0x2a, 0x45, 0xfb, 0x10, 0x29, 0x8d, 0xa5, 0xee, 0xf6,
	0x22, 0x11, 0x0e, 0xbb, 0x03, 0xc2, 0xe8, 0x40, 0x57, 0x36, 0x6a, 0xa0, 0x71, 0xa5, 0xb3, 0x69,
	0x3a, 0xed, 0xb4, 0xf1, 0xdc, 0xd4, 0x51, 0x03, 0x6e, 0x12, 0xde, 0x9f, 0xd5, 0x16, 0x8d, 0xf6,
	0x26, 0xe1, 0xfd, 0x9c, 0xb2, 0xbe, 0x05, 0xef, 0x18, 0xac, 0xd7, 0x29, 0x27, 0x0f, 0x89, 0xcc,
	0x80, 0x29, 0xbc, 0x3b, 0xdf, 0xb0, 0xb4, 0x47, 0xb0, 0xa4, 0xb2, 0xa2, 0x41, 0x2d, 0xb7, 0xf6,
	0xfc, 0x85, 0x11, 0xf8, 0xce, 0xa0, 0x5d, 0x3a, 0xfb, 0x75, 0xbf, 0xf0, 0xed, 0xef, 0xf7, 0xc7,
	0xa0, 0x33, 0x75, 0x70, 0x04, 0xcf, 0xb4, 0x26, 0x4a, 0x13, 0xa9, 0x32, 0x82, 0x77, 0x96, 0x20,
	0xd7, 0xb0, 0x04, 0x2f, 0x61, 0x09, 0x67, 0xc5, 0x0a, 0xa8, 0x15, 0x1b, 0xe5, 0xd6, 0xee, 0x12,
	0x82, 0xcc, 0x60, 0x06, 0xc0, 0x19, 0xb4, 0xfe, 0x15, 0xe1, 0x55, 0xf3, 0x10, 0xfa, 0x0a, 0x60,
	0x39, 0x97, 0x0f, 0x6a, 0x2d, 0x31, 0x5d, 0x10, 0x74, 0xf5, 0x70, 0xad, 0x3b, 0x17, 0x7f, 0xa8,
	0xbe, 0xff, 0xe1, 0xc7, 0x9f, 0x4f, 0x1b, 0x0f, 0xd1, 0x5e, 0x36, 0x5d, 0xf3, 0x53, 0x96, 0x1f,
	0x0f, 0xf4, 0x05, 0xc0, 0x92, 0xfb, 0xaa, 0xe8, 0xc9, 0xaa, 0x07, 0xe7, 0xa3, 0xad, 0x36, 0xd7,
	0xb8, 0x61, 0x01, 0x1f, 0x19, 0xc0, 0x5d, 0xb4, 0xb3, 0x08, 0xd0, 0xe5, 0x69, 0xe8, 0x5c, 0x64,
	0xab, 0xe9, 0xe6, 0x63, 0x5f, 0x4d, 0x77, 0x69, 0x1e, 0x56, 0xd3, 0xb9, 0xb0, 0xdb, 0x6f, 0xce,
	0xc6, 0x1e, 0x38, 0x1f, 0x7b, 0xe0, 0xf7, 0xd8, 0x03, 0x1f, 0x27, 0x5e, 0xe1, 0x7c, 0xe2, 0x15,
	0x7e, 0x4e, 0xbc, 0xc2, 0xdb, 0xa7, 0x94, 0xe9, 0x41, 0xd2, 0xf3, 0x43, 0x11, 0x3b, 0x1b, 0x2a,
	0x0e, 0xc8, 0x7b, 0x12, 0x26, 0xe9, 0x2e, 0x38, 0xc0, 0xbd, 0x90, 0x05, 0xb1, 0xe8, 0x27, 0x11,
	0x51, 0x33, 0x0f, 0x98, 0x15, 0xd0, 0xbb, 0x66, 0x76, 0xc0, 0xe1, 0xff, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd1, 0x1f, 0xb0, 0x5d, 0xb5, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// IsMigrating queries the sequencer changes.
	IsMigrating(ctx context.Context, in *QueryIsMigratingRequest, opts ...grpc.CallOption) (*QueryIsMigratingResponse, error)
	// Sequencer queries the sequencer.
	Sequencer(ctx context.Context, in *QuerySequencerRequest, opts ...grpc.CallOption) (*QuerySequencerResponse, error)
	// Attesters queries the list of attesters.
	Attesters(ctx context.Context, in *QueryAttestersRequest, opts ...grpc.CallOption) (*QueryAttestersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) IsMigrating(ctx context.Context, in *QueryIsMigratingRequest, opts ...grpc.CallOption) (*QueryIsMigratingResponse, error) {
	out := new(QueryIsMigratingResponse)
	err := c.cc.Invoke(ctx, "/rollkitsdk.rollkitmngr.v1.Query/IsMigrating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Sequencer(ctx context.Context, in *QuerySequencerRequest, opts ...grpc.CallOption) (*QuerySequencerResponse, error) {
	out := new(QuerySequencerResponse)
	err := c.cc.Invoke(ctx, "/rollkitsdk.rollkitmngr.v1.Query/Sequencer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Attesters(ctx context.Context, in *QueryAttestersRequest, opts ...grpc.CallOption) (*QueryAttestersResponse, error) {
	out := new(QueryAttestersResponse)
	err := c.cc.Invoke(ctx, "/rollkitsdk.rollkitmngr.v1.Query/Attesters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// IsMigrating queries the sequencer changes.
	IsMigrating(context.Context, *QueryIsMigratingRequest) (*QueryIsMigratingResponse, error)
	// Sequencer queries the sequencer.
	Sequencer(context.Context, *QuerySequencerRequest) (*QuerySequencerResponse, error)
	// Attesters queries the list of attesters.
	Attesters(context.Context, *QueryAttestersRequest) (*QueryAttestersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) IsMigrating(ctx context.Context, req *QueryIsMigratingRequest) (*QueryIsMigratingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsMigrating not implemented")
}
func (*UnimplementedQueryServer) Sequencer(ctx context.Context, req *QuerySequencerRequest) (*QuerySequencerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sequencer not implemented")
}
func (*UnimplementedQueryServer) Attesters(ctx context.Context, req *QueryAttestersRequest) (*QueryAttestersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attesters not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_IsMigrating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIsMigratingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IsMigrating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollkitsdk.rollkitmngr.v1.Query/IsMigrating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IsMigrating(ctx, req.(*QueryIsMigratingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Sequencer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySequencerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Sequencer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollkitsdk.rollkitmngr.v1.Query/Sequencer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Sequencer(ctx, req.(*QuerySequencerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Attesters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAttestersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Attesters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollkitsdk.rollkitmngr.v1.Query/Attesters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Attesters(ctx, req.(*QueryAttestersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rollkitsdk.rollkitmngr.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsMigrating",
			Handler:    _Query_IsMigrating_Handler,
		},
		{
			MethodName: "Sequencer",
			Handler:    _Query_Sequencer_Handler,
		},
		{
			MethodName: "Attesters",
			Handler:    _Query_Attesters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollkitsdk/rollkitmngr/v1/query.proto",
}

func (m *QueryIsMigratingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsMigratingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsMigratingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIsMigratingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsMigratingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsMigratingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndBlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EndBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.StartBlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StartBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.IsMigrating {
		i--
		if m.IsMigrating {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QuerySequencerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySequencerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Sequencer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAttestersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAttestersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attesters) > 0 {
		for iNdEx := len(m.Attesters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attesters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryIsMigratingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIsMigratingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsMigrating {
		n += 2
	}
	if m.StartBlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.StartBlockHeight))
	}
	if m.EndBlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.EndBlockHeight))
	}
	return n
}

func (m *QuerySequencerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySequencerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Sequencer.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAttestersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAttestersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Attesters) > 0 {
		for _, e := range m.Attesters {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryIsMigratingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsMigratingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsMigratingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsMigratingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsMigratingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsMigratingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsMigrating", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsMigrating = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlockHeight", wireType)
			}
			m.StartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlockHeight", wireType)
			}
			m.EndBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sequencer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attesters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attesters = append(m.Attesters, Attester{})
			if err := m.Attesters[len(m.Attesters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
