// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollkitsdk/rollkitmngr/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgMigrateToRollkit is the Msg/MsgMigrateToRollkit request type.
type MsgMigrateToRollkit struct {
	// authority is the address that controls the module (defaults to x/gov unless
	// overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// block height that trigger the rollkit migration.
	// When IBC is enabled, the migration can take several blocks to complete.
	// This is the block height at which the migration will be triggered.
	BlockHeight uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// sequencer is the pubkey that will become new sequencer.
	Sequencer Sequencer `protobuf:"bytes,3,opt,name=sequencer,proto3" json:"sequencer"`
	// attesters is the list of attesters that will attest to blocks.
	Attesters []Attester `protobuf:"bytes,4,rep,name=attesters,proto3" json:"attesters"`
}

func (m *MsgMigrateToRollkit) Reset()         { *m = MsgMigrateToRollkit{} }
func (m *MsgMigrateToRollkit) String() string { return proto.CompactTextString(m) }
func (*MsgMigrateToRollkit) ProtoMessage()    {}
func (*MsgMigrateToRollkit) Descriptor() ([]byte, []int) {
	return fileDescriptor_43700acb817b0d03, []int{0}
}
func (m *MsgMigrateToRollkit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMigrateToRollkit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMigrateToRollkit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMigrateToRollkit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMigrateToRollkit.Merge(m, src)
}
func (m *MsgMigrateToRollkit) XXX_Size() int {
	return m.Size()
}
func (m *MsgMigrateToRollkit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMigrateToRollkit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMigrateToRollkit proto.InternalMessageInfo

func (m *MsgMigrateToRollkit) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgMigrateToRollkit) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MsgMigrateToRollkit) GetSequencer() Sequencer {
	if m != nil {
		return m.Sequencer
	}
	return Sequencer{}
}

func (m *MsgMigrateToRollkit) GetAttesters() []Attester {
	if m != nil {
		return m.Attesters
	}
	return nil
}

// MsgMigrateToRollkitResponse defines the response structure for executing a
// MsgRollkitMigrate message.
type MsgMigrateToRollkitResponse struct {
}

func (m *MsgMigrateToRollkitResponse) Reset()         { *m = MsgMigrateToRollkitResponse{} }
func (m *MsgMigrateToRollkitResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMigrateToRollkitResponse) ProtoMessage()    {}
func (*MsgMigrateToRollkitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43700acb817b0d03, []int{1}
}
func (m *MsgMigrateToRollkitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMigrateToRollkitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMigrateToRollkitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMigrateToRollkitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMigrateToRollkitResponse.Merge(m, src)
}
func (m *MsgMigrateToRollkitResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMigrateToRollkitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMigrateToRollkitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMigrateToRollkitResponse proto.InternalMessageInfo

// MsgEditAttesters is the Msg/EditAttesters request type.
type MsgEditAttesters struct {
	// authority is the address that controls the module (defaults to x/gov unless
	// overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// attesters is the list of attesters to add or remove.
	Attesters []Attester `protobuf:"bytes,2,rep,name=attesters,proto3" json:"attesters"`
}

func (m *MsgEditAttesters) Reset()         { *m = MsgEditAttesters{} }
func (m *MsgEditAttesters) String() string { return proto.CompactTextString(m) }
func (*MsgEditAttesters) ProtoMessage()    {}
func (*MsgEditAttesters) Descriptor() ([]byte, []int) {
	return fileDescriptor_43700acb817b0d03, []int{2}
}
func (m *MsgEditAttesters) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEditAttesters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEditAttesters.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEditAttesters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEditAttesters.Merge(m, src)
}
func (m *MsgEditAttesters) XXX_Size() int {
	return m.Size()
}
func (m *MsgEditAttesters) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEditAttesters.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEditAttesters proto.InternalMessageInfo

func (m *MsgEditAttesters) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgEditAttesters) GetAttesters() []Attester {
	if m != nil {
		return m.Attesters
	}
	return nil
}

// MsgEditAttestersResponse defines the response structure for executing a
// MsgEditAttesters message.
type MsgEditAttestersResponse struct {
}

func (m *MsgEditAttestersResponse) Reset()         { *m = MsgEditAttestersResponse{} }
func (m *MsgEditAttestersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgEditAttestersResponse) ProtoMessage()    {}
func (*MsgEditAttestersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43700acb817b0d03, []int{3}
}
func (m *MsgEditAttestersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEditAttestersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEditAttestersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEditAttestersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEditAttestersResponse.Merge(m, src)
}
func (m *MsgEditAttestersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEditAttestersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEditAttestersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEditAttestersResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgMigrateToRollkit)(nil), "rollkitsdk.rollkitmngr.v1.MsgMigrateToRollkit")
	proto.RegisterType((*MsgMigrateToRollkitResponse)(nil), "rollkitsdk.rollkitmngr.v1.MsgMigrateToRollkitResponse")
	proto.RegisterType((*MsgEditAttesters)(nil), "rollkitsdk.rollkitmngr.v1.MsgEditAttesters")
	proto.RegisterType((*MsgEditAttestersResponse)(nil), "rollkitsdk.rollkitmngr.v1.MsgEditAttestersResponse")
}

func init() {
	proto.RegisterFile("rollkitsdk/rollkitmngr/v1/tx.proto", fileDescriptor_43700acb817b0d03)
}

var fileDescriptor_43700acb817b0d03 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xce, 0x25, 0x05, 0xc9, 0x17, 0x90, 0x8a, 0xa9, 0x84, 0x6b, 0x84, 0x1b, 0x0c, 0x48, 0x51,
	0x50, 0x6c, 0x35, 0x15, 0x1d, 0x18, 0x90, 0x1a, 0x09, 0x89, 0x01, 0x2f, 0x2e, 0x03, 0x62, 0xa9,
	0x1c, 0xfb, 0x74, 0x39, 0x25, 0xf6, 0xa5, 0xf7, 0xce, 0x55, 0xcb, 0x84, 0x18, 0x99, 0xf8, 0x33,
	0x18, 0x33, 0xf0, 0x27, 0x30, 0x74, 0x60, 0xa8, 0x98, 0x98, 0x10, 0x4a, 0x86, 0xfc, 0x11, 0x2c,
	0x28, 0xfe, 0x41, 0x70, 0x13, 0x2c, 0x85, 0x2e, 0xd6, 0xdd, 0xf7, 0x3e, 0x7f, 0xef, 0x7d, 0x9f,
	0xee, 0x61, 0x53, 0xf0, 0xe1, 0x70, 0xc0, 0x24, 0x04, 0x03, 0x3b, 0x3b, 0x86, 0x11, 0x15, 0xf6,
	0xc9, 0xae, 0x2d, 0x4f, 0xad, 0x91, 0xe0, 0x92, 0xab, 0xdb, 0x0b, 0x8e, 0xf5, 0x17, 0xc7, 0x3a,
	0xd9, 0xd5, 0x6f, 0x79, 0x21, 0x8b, 0xb8, 0x9d, 0x7c, 0x53, 0xb6, 0x7e, 0xc7, 0xe7, 0x10, 0x72,
	0xb0, 0x43, 0xa0, 0x73, 0x95, 0x10, 0x68, 0x56, 0xd8, 0x4e, 0x0b, 0x47, 0xc9, 0xcd, 0x4e, 0x2f,
	0x59, 0x69, 0x8b, 0x72, 0xca, 0x53, 0x7c, 0x7e, 0xca, 0xd0, 0x47, 0x25, 0xb3, 0x9d, 0x8d, 0x48,
	0xf6, 0xb3, 0xf9, 0xa5, 0x8a, 0x6f, 0x3b, 0x40, 0x1d, 0x46, 0x85, 0x27, 0xc9, 0x2b, 0xee, 0xa6,
	0x54, 0x75, 0x1f, 0x2b, 0x5e, 0x2c, 0xfb, 0x5c, 0x30, 0x79, 0xa6, 0xa1, 0x06, 0x6a, 0x2a, 0x5d,
	0xed, 0xdb, 0xe7, 0xf6, 0x56, 0xd6, 0xf9, 0x20, 0x08, 0x04, 0x01, 0x38, 0x94, 0x82, 0x45, 0xd4,
	0x5d, 0x50, 0xd5, 0xfb, 0xf8, 0x46, 0x6f, 0xc8, 0xfd, 0xc1, 0x51, 0x9f, 0x30, 0xda, 0x97, 0x5a,
	0xb5, 0x81, 0x9a, 0x1b, 0x6e, 0x3d, 0xc1, 0x5e, 0x24, 0x90, 0xea, 0x60, 0x05, 0xc8, 0x71, 0x4c,
	0x22, 0x9f, 0x08, 0xad, 0xd6, 0x40, 0xcd, 0x7a, 0xe7, 0xa1, 0xf5, 0xcf, 0x94, 0xac, 0xc3, 0x9c,
	0xdb, 0x55, 0xce, 0x7f, 0xec, 0x54, 0x3e, 0xcd, 0xc6, 0x2d, 0xe4, 0x2e, 0x14, 0xd4, 0x97, 0x58,
	0xf1, 0xa4, 0x24, 0x20, 0x89, 0x00, 0x6d, 0xa3, 0x51, 0x6b, 0xd6, 0x3b, 0x0f, 0x4a, 0xe4, 0x0e,
	0x32, 0x6e, 0x41, 0xed, 0x8f, 0xc0, 0xd3, 0x27, 0xef, 0x67, 0xe3, 0xd6, 0xc2, 0xcf, 0x87, 0xd9,
	0xb8, 0x65, 0x5e, 0x8a, 0x6f, 0x45, 0x5c, 0xe6, 0x3d, 0x7c, 0x77, 0x05, 0xec, 0x12, 0x18, 0xf1,
	0x08, 0x88, 0xf9, 0x15, 0xe1, 0x4d, 0x07, 0xe8, 0xf3, 0x80, 0xc9, 0xbc, 0x3f, 0xfc, 0x77, 0xc4,
	0x05, 0xc3, 0xd5, 0xab, 0x1a, 0xee, 0x2c, 0x1b, 0xde, 0x59, 0x36, 0x5c, 0x98, 0xdc, 0xd4, 0xb1,
	0x76, 0x19, 0xcb, 0xad, 0x76, 0x7e, 0x21, 0x5c, 0x73, 0x80, 0xaa, 0x6f, 0xf1, 0xe6, 0xd2, 0xa3,
	0xb2, 0x4a, 0xc6, 0x5c, 0x11, 0x9f, 0xbe, 0xbf, 0x1e, 0x3f, 0x9f, 0x41, 0x3d, 0xc6, 0x37, 0x8b,
	0x51, 0x3f, 0x2e, 0x17, 0x2a, 0x90, 0xf5, 0xbd, 0x35, 0xc8, 0x79, 0x4b, 0xfd, 0xda, 0xbb, 0x79,
	0xb0, 0xdd, 0xd7, 0xe7, 0x13, 0x03, 0x5d, 0x4c, 0x0c, 0xf4, 0x73, 0x62, 0xa0, 0x8f, 0x53, 0xa3,
	0x72, 0x31, 0x35, 0x2a, 0xdf, 0xa7, 0x46, 0xe5, 0xcd, 0x33, 0xca, 0x64, 0x3f, 0xee, 0x59, 0x3e,
	0x0f, 0xf3, 0x7d, 0xb4, 0x29, 0x6f, 0x93, 0x53, 0xe2, 0xc7, 0x92, 0xf1, 0xa8, 0xed, 0xf5, 0x7c,
	0x66, 0x87, 0x3c, 0x88, 0x87, 0x04, 0x0a, 0x1b, 0x9b, 0xac, 0x6b, 0xef, 0x7a, 0xb2, 0xaf, 0x7b,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xdd, 0x78, 0xaa, 0x74, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// MigrateToRollkit defines a (governance) operation for the migration to rollkit. The authority defaults to the x/gov module account.
	MigrateToRollkit(ctx context.Context, in *MsgMigrateToRollkit, opts ...grpc.CallOption) (*MsgMigrateToRollkitResponse, error)
	// EditAttesters defines a governance operation to edit the list of attesters.
	EditAttesters(ctx context.Context, in *MsgEditAttesters, opts ...grpc.CallOption) (*MsgEditAttestersResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) MigrateToRollkit(ctx context.Context, in *MsgMigrateToRollkit, opts ...grpc.CallOption) (*MsgMigrateToRollkitResponse, error) {
	out := new(MsgMigrateToRollkitResponse)
	err := c.cc.Invoke(ctx, "/rollkitsdk.rollkitmngr.v1.Msg/MigrateToRollkit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EditAttesters(ctx context.Context, in *MsgEditAttesters, opts ...grpc.CallOption) (*MsgEditAttestersResponse, error) {
	out := new(MsgEditAttestersResponse)
	err := c.cc.Invoke(ctx, "/rollkitsdk.rollkitmngr.v1.Msg/EditAttesters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// MigrateToRollkit defines a (governance) operation for the migration to rollkit. The authority defaults to the x/gov module account.
	MigrateToRollkit(context.Context, *MsgMigrateToRollkit) (*MsgMigrateToRollkitResponse, error)
	// EditAttesters defines a governance operation to edit the list of attesters.
	EditAttesters(context.Context, *MsgEditAttesters) (*MsgEditAttestersResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) MigrateToRollkit(ctx context.Context, req *MsgMigrateToRollkit) (*MsgMigrateToRollkitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateToRollkit not implemented")
}
func (*UnimplementedMsgServer) EditAttesters(ctx context.Context, req *MsgEditAttesters) (*MsgEditAttestersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditAttesters not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_MigrateToRollkit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMigrateToRollkit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MigrateToRollkit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollkitsdk.rollkitmngr.v1.Msg/MigrateToRollkit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MigrateToRollkit(ctx, req.(*MsgMigrateToRollkit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EditAttesters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEditAttesters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EditAttesters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollkitsdk.rollkitmngr.v1.Msg/EditAttesters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EditAttesters(ctx, req.(*MsgEditAttesters))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rollkitsdk.rollkitmngr.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MigrateToRollkit",
			Handler:    _Msg_MigrateToRollkit_Handler,
		},
		{
			MethodName: "EditAttesters",
			Handler:    _Msg_EditAttesters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollkitsdk/rollkitmngr/v1/tx.proto",
}

func (m *MsgMigrateToRollkit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMigrateToRollkit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMigrateToRollkit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attesters) > 0 {
		for iNdEx := len(m.Attesters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attesters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.Sequencer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMigrateToRollkitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMigrateToRollkitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMigrateToRollkitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgEditAttesters) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEditAttesters) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEditAttesters) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attesters) > 0 {
		for iNdEx := len(m.Attesters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attesters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEditAttestersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEditAttestersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEditAttestersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgMigrateToRollkit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	l = m.Sequencer.Size()
	n += 1 + l + sovTx(uint64(l))
	if len(m.Attesters) > 0 {
		for _, e := range m.Attesters {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgMigrateToRollkitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgEditAttesters) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Attesters) > 0 {
		for _, e := range m.Attesters {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgEditAttestersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgMigrateToRollkit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMigrateToRollkit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMigrateToRollkit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sequencer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attesters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attesters = append(m.Attesters, Attester{})
			if err := m.Attesters[len(m.Attesters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMigrateToRollkitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMigrateToRollkitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMigrateToRollkitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEditAttesters) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEditAttesters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEditAttesters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attesters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attesters = append(m.Attesters, Attester{})
			if err := m.Attesters[len(m.Attesters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEditAttestersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEditAttestersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEditAttestersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
