// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollkitsdk/rollkitmngr/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRollkitMigrate is the Msg/RollkitMigrate request type.
type MsgRollkitMigrate struct {
	// authority is the address that controls the module (defaults to x/gov unless
	// overwritten).
	Authority   string    `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	BlockHeight uint64    `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Sequencer   Sequencer `protobuf:"bytes,3,opt,name=sequencer,proto3" json:"sequencer"`
	// attesters is the list of attesters that will attest to blocks.
	Attesters []Attester `protobuf:"bytes,4,rep,name=attesters,proto3" json:"attesters"`
}

func (m *MsgRollkitMigrate) Reset()         { *m = MsgRollkitMigrate{} }
func (m *MsgRollkitMigrate) String() string { return proto.CompactTextString(m) }
func (*MsgRollkitMigrate) ProtoMessage()    {}
func (*MsgRollkitMigrate) Descriptor() ([]byte, []int) {
	return fileDescriptor_43700acb817b0d03, []int{0}
}
func (m *MsgRollkitMigrate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRollkitMigrate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRollkitMigrate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRollkitMigrate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRollkitMigrate.Merge(m, src)
}
func (m *MsgRollkitMigrate) XXX_Size() int {
	return m.Size()
}
func (m *MsgRollkitMigrate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRollkitMigrate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRollkitMigrate proto.InternalMessageInfo

func (m *MsgRollkitMigrate) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRollkitMigrate) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MsgRollkitMigrate) GetSequencer() Sequencer {
	if m != nil {
		return m.Sequencer
	}
	return Sequencer{}
}

func (m *MsgRollkitMigrate) GetAttesters() []Attester {
	if m != nil {
		return m.Attesters
	}
	return nil
}

// MsgMigrateToRollkitResponse defines the response structure for executing a
// MsgRollkitMigrate message.
type MsgMigrateToRollkitResponse struct {
}

func (m *MsgMigrateToRollkitResponse) Reset()         { *m = MsgMigrateToRollkitResponse{} }
func (m *MsgMigrateToRollkitResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMigrateToRollkitResponse) ProtoMessage()    {}
func (*MsgMigrateToRollkitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43700acb817b0d03, []int{1}
}
func (m *MsgMigrateToRollkitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMigrateToRollkitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMigrateToRollkitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMigrateToRollkitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMigrateToRollkitResponse.Merge(m, src)
}
func (m *MsgMigrateToRollkitResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMigrateToRollkitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMigrateToRollkitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMigrateToRollkitResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRollkitMigrate)(nil), "rollkitsdk.rollkitmngr.v1.MsgRollkitMigrate")
	proto.RegisterType((*MsgMigrateToRollkitResponse)(nil), "rollkitsdk.rollkitmngr.v1.MsgMigrateToRollkitResponse")
}

func init() {
	proto.RegisterFile("rollkitsdk/rollkitmngr/v1/tx.proto", fileDescriptor_43700acb817b0d03)
}

var fileDescriptor_43700acb817b0d03 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x4d, 0x41, 0xf2, 0x85, 0x81, 0x5a, 0x95, 0x70, 0x83, 0x30, 0x26, 0x80, 0x14,
	0x45, 0xc4, 0xa7, 0xa6, 0x52, 0x07, 0x06, 0xa4, 0x66, 0x62, 0xc0, 0x8b, 0xcb, 0x80, 0x58, 0x2a,
	0xc7, 0x39, 0x5d, 0x4e, 0xb1, 0xfd, 0xc2, 0xbd, 0x73, 0x95, 0x6e, 0x88, 0x81, 0x81, 0x89, 0x8f,
	0xc1, 0x98, 0x81, 0x0f, 0xc0, 0xd8, 0xb1, 0x62, 0x62, 0x42, 0x28, 0x19, 0xf2, 0x35, 0x50, 0xec,
	0x2b, 0xa6, 0xad, 0xea, 0xc5, 0xba, 0xf7, 0xfe, 0x3f, 0xff, 0xef, 0xdd, 0xd3, 0x9f, 0x76, 0x14,
	0x24, 0xc9, 0x54, 0x6a, 0x1c, 0x4f, 0x99, 0x39, 0xa6, 0x99, 0x50, 0xec, 0x74, 0x9f, 0xe9, 0xb9,
	0x3f, 0x53, 0xa0, 0xc1, 0xde, 0xab, 0x18, 0xff, 0x3f, 0xc6, 0x3f, 0xdd, 0x6f, 0xef, 0x44, 0xa9,
	0xcc, 0x80, 0x15, 0xdf, 0x92, 0x6e, 0x3f, 0x88, 0x01, 0x53, 0x40, 0x96, 0xa2, 0xd8, 0xb8, 0xa4,
	0x28, 0x8c, 0xb0, 0x57, 0x0a, 0x27, 0x45, 0xc5, 0xca, 0xc2, 0x48, 0xbb, 0x02, 0x04, 0x94, 0xfd,
	0xcd, 0xc9, 0x74, 0x9f, 0xd7, 0xcc, 0x76, 0x36, 0xe3, 0xe6, 0xe7, 0xce, 0x8f, 0x2d, 0xba, 0x13,
	0xa0, 0x08, 0x4b, 0x22, 0x90, 0x42, 0x45, 0x9a, 0xdb, 0x87, 0xd4, 0x8a, 0x72, 0x3d, 0x01, 0x25,
	0xf5, 0x99, 0x43, 0x3c, 0xd2, 0xb5, 0x86, 0xce, 0xcf, 0xef, 0xfd, 0x5d, 0x73, 0xef, 0xd1, 0x78,
	0xac, 0x38, 0xe2, 0xb1, 0x56, 0x32, 0x13, 0x61, 0x85, 0xda, 0x4f, 0xe8, 0xbd, 0x51, 0x02, 0xf1,
	0xf4, 0x64, 0xc2, 0xa5, 0x98, 0x68, 0x67, 0xcb, 0x23, 0xdd, 0xed, 0xb0, 0x55, 0xf4, 0x5e, 0x17,
	0x2d, 0x3b, 0xa0, 0x16, 0xf2, 0x0f, 0x39, 0xcf, 0x62, 0xae, 0x9c, 0xa6, 0x47, 0xba, 0xad, 0xc1,
	0x33, 0xff, 0xd6, 0x1d, 0xf9, 0xc7, 0x97, 0xec, 0xd0, 0x3a, 0xff, 0xfd, 0xb8, 0xf1, 0x6d, 0xbd,
	0xe8, 0x91, 0xb0, 0x72, 0xb0, 0xdf, 0x50, 0x2b, 0xd2, 0x9a, 0xa3, 0xe6, 0x0a, 0x9d, 0x6d, 0xaf,
	0xd9, 0x6d, 0x0d, 0x9e, 0xd6, 0xd8, 0x1d, 0x19, 0xf6, 0x8a, 0xdb, 0x3f, 0x83, 0x97, 0x07, 0x9f,
	0xd6, 0x8b, 0x5e, 0xf5, 0x9e, 0x2f, 0xeb, 0x45, 0xcf, 0xbb, 0xb6, 0xbc, 0x1b, 0xcb, 0xea, 0x3c,
	0xa2, 0x0f, 0x03, 0x14, 0xa6, 0x7a, 0x0b, 0x46, 0x0d, 0x39, 0xce, 0x20, 0x43, 0x3e, 0xf8, 0x4c,
	0x68, 0x33, 0x40, 0x61, 0xcf, 0xe9, 0xfd, 0xeb, 0x8c, 0xfd, 0xa2, 0x66, 0xd4, 0x1b, 0x17, 0xb5,
	0x0f, 0xeb, 0xe9, 0xdb, 0x26, 0x68, 0xdf, 0xf9, 0xb8, 0x79, 0xe7, 0xf0, 0xdd, 0xf9, 0xd2, 0x25,
	0x17, 0x4b, 0x97, 0xfc, 0x59, 0xba, 0xe4, 0xeb, 0xca, 0x6d, 0x5c, 0xac, 0xdc, 0xc6, 0xaf, 0x95,
	0xdb, 0x78, 0xff, 0x4a, 0x48, 0x3d, 0xc9, 0x47, 0x7e, 0x0c, 0xe9, 0x65, 0x56, 0x98, 0x80, 0x3e,
	0x9f, 0xf3, 0x38, 0xd7, 0x12, 0xb2, 0x7e, 0x34, 0x8a, 0x25, 0x4b, 0x61, 0x9c, 0x27, 0x1c, 0xaf,
	0xa4, 0xa9, 0x88, 0xd2, 0xe8, 0x6e, 0x91, 0xa5, 0x83, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xea,
	0x3e, 0xa9, 0x1b, 0x10, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// MigrateToRollkit defines a (governance) operation for the migration to rollkit. The authority defaults to the x/gov module account.
	MigrateToRollkit(ctx context.Context, in *MsgRollkitMigrate, opts ...grpc.CallOption) (*MsgMigrateToRollkitResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) MigrateToRollkit(ctx context.Context, in *MsgRollkitMigrate, opts ...grpc.CallOption) (*MsgMigrateToRollkitResponse, error) {
	out := new(MsgMigrateToRollkitResponse)
	err := c.cc.Invoke(ctx, "/rollkitsdk.rollkitmngr.v1.Msg/MigrateToRollkit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// MigrateToRollkit defines a (governance) operation for the migration to rollkit. The authority defaults to the x/gov module account.
	MigrateToRollkit(context.Context, *MsgRollkitMigrate) (*MsgMigrateToRollkitResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) MigrateToRollkit(ctx context.Context, req *MsgRollkitMigrate) (*MsgMigrateToRollkitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateToRollkit not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_MigrateToRollkit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRollkitMigrate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MigrateToRollkit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rollkitsdk.rollkitmngr.v1.Msg/MigrateToRollkit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MigrateToRollkit(ctx, req.(*MsgRollkitMigrate))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rollkitsdk.rollkitmngr.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MigrateToRollkit",
			Handler:    _Msg_MigrateToRollkit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollkitsdk/rollkitmngr/v1/tx.proto",
}

func (m *MsgRollkitMigrate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRollkitMigrate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRollkitMigrate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attesters) > 0 {
		for iNdEx := len(m.Attesters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attesters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.Sequencer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMigrateToRollkitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMigrateToRollkitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMigrateToRollkitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRollkitMigrate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	l = m.Sequencer.Size()
	n += 1 + l + sovTx(uint64(l))
	if len(m.Attesters) > 0 {
		for _, e := range m.Attesters {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgMigrateToRollkitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRollkitMigrate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRollkitMigrate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRollkitMigrate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sequencer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attesters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attesters = append(m.Attesters, Attester{})
			if err := m.Attesters[len(m.Attesters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMigrateToRollkitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMigrateToRollkitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMigrateToRollkitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
